### ISSUE TITLE
[Bug] Error adding movie to Radarr (HTTP 400 Bad Response)

### ISSUE THREAD

**Issue by simonk83** [CometTools/LunaSea#611]
**Describe the Bug**
Trying to add a movie this morning and it gives me the below error

**To Reproduce**
I tried with both search for missing checked and unchecked

**Expected Behaviour**
Movie added as normal 

**Screenshots**

**Versions**
LunaSea: 6.0.0(60000006)
Radar: 4.0.1.5772

I can try and update Radarr to the latest first if you like, but I’ll hold off for now. Not sure if these latest builds of Radarr have changed the api slightly or something along those lines. I can update LunaSea through Testflight if that helps.

EDIT: I just installed the Mac app (6.0.0(1000000560) and the same error occurs.

**Additional context**
DioError [DioErrorType.response]: Http status error [400]
Source stack:
#0      DioMixin.fetch (package:dio/src/dio_mixin.dart:473)
#1      DioMixin.request (package:dio/src/dio_mixin.dart:468)
#2      DioMixin.post (package:dio/src/dio_mixin.dart:91)
#3      _commandAddMovie (package:radarr/src/commands/movie/add_movie.dart:23)
#4      RadarrCommandHandler_Movie.create (package:radarr/src/commands/movie.dart:71)
#5      RadarrAPIHelper.addMovie (package:lunasea/modules/radarr/core/api_helper.dart:105)
#6      RadarrAddMovieDetailsActionBar._onTap (package:lunasea/modules/radarr/routes/add_movie_details/widgets/bottom_action_bar.dart:35)
#7      RadarrAddMovieDetailsActionBar.build.<anonymous closure> (package:lunasea/modules/radarr/routes/add_movie_details/widgets/bottom_action_bar.dart:23)
#8      RadarrAddMovieDetailsActionBar.build.<anonymous closure> (package:lunasea/modules/radarr/routes/add_movie_details/widgets/bottom_action_bar.dart:23)
#9      new LunaButton._.<anonymous closure> (package:lunasea/core/ui/button.dart:39)
#10     new LunaButton._.<anonymous closure> (package:lunasea/core/ui/button.dart:36)
#11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989)
#12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198)
#13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608)
#14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296)
#15     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267)
#16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:443)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:419)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:322)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279)
#24     _rootRunUnary (dart:async/zone.dart:1442)
#25     _CustomZone.runUnary (dart:async/zone.dart:1335)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#27     _invoke1 (dart:ui/hooks.dart:170)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:94)

**Comment by simonk83** [comment]
Turns out this is because I had it set to PreDB as the Availability (thanks to the guys in your discord). Changed that and it's fine now.
